[Station_G3_ESP32]
extends = esp32_base
board = station-g3-esp32
build_flags =
  ${esp32_base.build_flags}
  ${sensor_base.build_flags}
  -I variants/station_g3_esp32
  -I src/helpers/ui
  -D STATION_G3_ESP32
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D P_LORA_DIO_1=48
  -D P_LORA_NSS=11
  -D P_LORA_RESET=21
  -D P_LORA_BUSY=47
  -D P_LORA_SCLK=12
  -D P_LORA_MISO=14
  -D P_LORA_MOSI=13
  -D P_PA1_EN=9 ; PA PL1 Mode: LOW/open selects low level, HIGH/short selects high level.
  -D P_PA1_EN_ACTIVE=HIGH
  -D P_PRIMARY_LNA_EN=10 ; Primary Slot LNA Mode: LOW/open is LNA on, HIGH/short is LNA off.
  -D P_PRIMARY_LNA_EN_ACTIVE=LOW
  -D LORA_TX_POWER=7 ; SX1262 input power to the Station G3 PA; final output depends on PA PL1/PL2 level.
  -D MAX_LORA_TX_POWER=22
;  -D P_LORA_TX_LED=35
  -D PIN_BOARD_SDA=5
  -D PIN_BOARD_SCL=6
  -D PIN_USER_BTN=38
  -D PIN_GPS_RX=15
  -D PIN_GPS_TX=7
  -D SX126X_DIO2_AS_RF_SWITCH=true
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=0
  -D DISPLAY_CLASS=SH1106Display
build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/station_g3_esp32>
  +<helpers/sensors>
  +<helpers/ui/SH1106Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
lib_deps =
  ${esp32_base.lib_deps}
  ${sensor_base.lib_deps}
  adafruit/Adafruit SH110X @ ~2.1.13
  adafruit/Adafruit GFX Library @ ^1.12.1

[env:Station_G3_ESP32_repeater]
extends = Station_G3_ESP32
build_flags =
  ${Station_G3_ESP32.build_flags}
  -D ADVERT_NAME='"Station G3 ESP32 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${Station_G3_ESP32.build_src_filter}
  +<../examples/simple_repeater>
lib_deps =
  ${Station_G3_ESP32.lib_deps}
  ${esp32_ota.lib_deps}

[env:Station_G3_ESP32_logging_repeater]
extends = Station_G3_ESP32
build_flags =
  ${Station_G3_ESP32.build_flags}
  -D ADVERT_NAME='"Station G3 ESP32 Logging Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${Station_G3_ESP32.build_src_filter}
  +<../examples/simple_repeater>
lib_deps =
  ${Station_G3_ESP32.lib_deps}
  ${esp32_ota.lib_deps}

[env:Station_G3_ESP32_room_server]
extends = Station_G3_ESP32
build_src_filter = ${Station_G3_ESP32.build_src_filter}
  +<../examples/simple_room_server>
build_flags =
  ${Station_G3_ESP32.build_flags}
  -D ADVERT_NAME='"Station G3 ESP32 Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
lib_deps =
  ${Station_G3_ESP32.lib_deps}
  ${esp32_ota.lib_deps}

[env:Station_G3_ESP32_companion_radio_usb]
extends = Station_G3_ESP32
build_flags =
  ${Station_G3_ESP32.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D ENABLE_USB_INTERFACE
; NOTE: DO NOT ENABLE -->  -D MESH_PACKET_LOGGING=1
; NOTE: DO NOT ENABLE -->  -D MESH_DEBUG=1
build_src_filter = ${Station_G3_ESP32.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Station_G3_ESP32.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Station_G3_ESP32_companion_radio_ble]
extends = Station_G3_ESP32
build_flags =
  ${Station_G3_ESP32.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${Station_G3_ESP32.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Station_G3_ESP32.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Station_G3_ESP32_companion_radio_wifi]
extends = Station_G3_ESP32
build_flags =
  ${Station_G3_ESP32.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D WIFI_DEBUG_LOGGING=1
  -D WIFI_SSID='"myssid"'
  -D WIFI_PWD='"mypwd"'
  -D OFFLINE_QUEUE_SIZE=256
; -D MESH_PACKET_LOGGING=1
; -D MESH_DEBUG=1
build_src_filter = ${Station_G3_ESP32.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Station_G3_ESP32.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Station_G3_ESP32_kiss_modem]
extends = Station_G3_ESP32
build_src_filter = ${Station_G3_ESP32.build_src_filter}
  +<../examples/kiss_modem/>
