[WioTrackerL1]
extends = nrf52_base
board = seeed-wio-tracker-l1
board_build.ldscript = boards/nrf52840_s140_v7.ld
build_flags = ${nrf52_base.build_flags}
  ${sensor_base.build_flags}
  -I lib/nrf52/s140_nrf52_7.3.0_API/include
  -I lib/nrf52/s140_nrf52_7.3.0_API/include/nrf52
  -I variants/wio-tracker-l1
  -D WIO_TRACKER_L1
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
  -D PIN_OLED_RESET=-1
  -D GPS_BAUD_RATE=9600
build_src_filter = ${nrf52_base.build_src_filter}
  +<WioTrackerL1Board.cpp>
  +<../variants/wio-tracker-l1>
  +<helpers/ui/SH1106Display.cpp>
  +<helpers/sensors>
lib_deps= ${nrf52_base.lib_deps}
  ${sensor_base.lib_deps}
  adafruit/Adafruit SH110X @ ^2.1.13
  adafruit/Adafruit GFX Library @ ^1.12.1

[env:WioTrackerL1_repeater]
extends = WioTrackerL1
build_src_filter = ${WioTrackerL1.build_src_filter}
  +<../examples/simple_repeater>
build_flags =
  ${WioTrackerL1.build_flags}
  -D ADVERT_NAME='"WioTrackerL1 Repeater"'
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D DISPLAY_CLASS=SH1106Display
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
lib_deps = ${WioTrackerL1.lib_deps}
  adafruit/RTClib @ ^2.1.3

[env:WioTrackerL1_room_server]
extends = WioTrackerL1
build_src_filter = ${WioTrackerL1.build_src_filter}
  +<../examples/simple_room_server>
build_flags = ${WioTrackerL1.build_flags}
  -D ADVERT_NAME='"WioTrackerL1 Room"'
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
  -D DISPLAY_CLASS=SH1106Display
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
lib_deps = ${WioTrackerL1.lib_deps}
  adafruit/RTClib @ ^2.1.3

[env:WioTrackerL1_companion_radio_usb]
extends = WioTrackerL1
board_build.ldscript = boards/nrf52840_s140_v7_extrafs.ld
board_upload.maximum_size = 708608
build_flags = ${WioTrackerL1.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D DISPLAY_CLASS=SH1106Display
  -D UI_HAS_JOYSTICK=1
  -D UI_NO_HIBERNATE
  -D OFFLINE_QUEUE_SIZE=256
  -D PIN_BUZZER=12
  -D QSPIFLASH=1
  -D ENABLE_USB_INTERFACE
; NOTE: DO NOT ENABLE -->  -D MESH_PACKET_LOGGING=1
; NOTE: DO NOT ENABLE -->  -D MESH_DEBUG=1
build_src_filter = ${WioTrackerL1.build_src_filter}
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
  +<helpers/ui/SH1106Display.cpp>
  +<helpers/ui/buzzer.cpp>
lib_deps = ${WioTrackerL1.lib_deps}
  adafruit/RTClib @ ^2.1.3
  densaugeo/base64 @ ~1.4.0
  end2endzone/NonBlockingRTTTL@^1.3.0

[env:WioTrackerL1_companion_radio_ble]
extends = WioTrackerL1
board_build.ldscript = boards/nrf52840_s140_v7_extrafs.ld
board_upload.maximum_size = 708608
build_flags = ${WioTrackerL1.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
  -D DISPLAY_CLASS=SH1106Display
  -D UI_HAS_JOYSTICK=1
  -D UI_NO_HIBERNATE
  -D PIN_BUZZER=12
  -D QSPIFLASH=1
  -D ADVERT_NAME='"@@MAC"'
  -D ENV_PIN_SDA=PIN_WIRE1_SDA
  -D ENV_PIN_SCL=PIN_WIRE1_SCL
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
build_src_filter = ${WioTrackerL1.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/ui/buzzer.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps = ${WioTrackerL1.lib_deps}
  adafruit/RTClib @ ^2.1.3
  densaugeo/base64 @ ~1.4.0
  end2endzone/NonBlockingRTTTL@^1.3.0

[env:WioTrackerL1_kiss_modem]
extends = WioTrackerL1
build_src_filter = ${WioTrackerL1.build_src_filter}
  +<../examples/kiss_modem/>
