[MeshTracker_X1]
extends = nrf52_base
board = seeed-mesh-tracker-x1
board_build.ldscript = boards/nrf52840_s140_v7.ld
build_flags = ${nrf52_base.build_flags}
  -I src/helpers/nrf52
  -I lib/nrf52/s140_nrf52_7.3.0_API/include
  -I lib/nrf52/s140_nrf52_7.3.0_API/include/nrf52
  -I variants/meshtracker_x1
  -I src/helpers/ui
  -D MESH_TRACKER_X1
  -D PIN_USER_BTN=6
  -D USER_BTN_PRESSED=HIGH
  -D PIN_STATUS_LED=24
  -D PIN_STATUS_LED_R=3 ; P0.3 red
  -D PIN_STATUS_LED_G=24 ; P0.24 green
  -D PIN_STATUS_LED_B=28 ; P0.28 blue
  -D RADIO_CLASS=CustomLR2021
  -D USE_LR2021
  -D WRAPPER_CLASS=CustomLR2021Wrapper
  -D LORA_TX_POWER=22
  -D P_LORA_BUSY=7 ; P0.7
  -D P_LORA_SCLK=11 ; P0.11
  -D P_LORA_NSS=12 ; P0.12
  -D P_LORA_DIO_1=33 ; P1.1
  -D P_LORA_MISO=40 ; P1.8
  -D P_LORA_MOSI=41 ; P1.9
  -D P_LORA_RESET=42 ; P1.10
  -D LR2021_IRQ_DIO=8         ; P1.1 is connected to LR2021 DIO8
  -D LR2021_TCXO_VOLTAGE=1.6f
  -D ENV_INCLUDE_GPS=1
build_src_filter = ${nrf52_base.build_src_filter}
  +<helpers/*.cpp>
  +<../variants/meshtracker_x1>
lib_deps = ${nrf52_base.lib_deps}
  https://github.com/adafruit/Adafruit_SPA06_003/archive/refs/tags/1.0.2.zip
debug_tool = jlink
upload_protocol = nrfutil

[env:MeshTracker_X1_repeater]
extends = MeshTracker_X1
build_flags = ${MeshTracker_X1.build_flags}
  -I examples/companion_radio/ui-orig
  -D ADVERT_NAME='"MeshTracker X1 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${MeshTracker_X1.build_src_filter}
  +<../examples/simple_repeater>
lib_deps = ${MeshTracker_X1.lib_deps}
  stevemarple/MicroNMEA @ ^2.0.6

[env:MeshTracker_X1_room_server]
extends = MeshTracker_X1
build_flags = ${MeshTracker_X1.build_flags}
  -I examples/companion_radio/ui-orig
  -D ADVERT_NAME='"MeshTracker X1 Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${MeshTracker_X1.build_src_filter}
  +<../examples/simple_room_server>
lib_deps = ${MeshTracker_X1.lib_deps}
  stevemarple/MicroNMEA @ ^2.0.6

[env:MeshTracker_X1_companion_radio_usb]
extends = MeshTracker_X1
board_build.ldscript = boards/nrf52840_s140_v7_extrafs.ld
board_upload.maximum_size = 708608
build_flags = ${MeshTracker_X1.build_flags}
  -I examples/companion_radio/ui-orig
  -D QSPIFLASH=1
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
  -D OFFLINE_QUEUE_SIZE=256
  -D DISPLAY_CLASS=NullDisplayDriver
  -D PIN_BUZZER=25
  -D HAS_DRV2605=1
  -D DRV2605_USE_LRA=1
  -D ENABLE_USB_INTERFACE
build_src_filter = ${MeshTracker_X1.build_src_filter}
  +<helpers/ui/buzzer.cpp>
  +<helpers/ui/NullDisplayDriver.cpp>
  +<helpers/ui/DRV2605Vibration.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-orig/*.cpp>
lib_deps = ${MeshTracker_X1.lib_deps}
  densaugeo/base64 @ ~1.4.0
  stevemarple/MicroNMEA @ ^2.0.6
  end2endzone/NonBlockingRTTTL@^1.3.0
  adafruit/Adafruit DRV2605 Library @ ^1.2.4

[env:MeshTracker_X1_companion_radio_ble]
extends = MeshTracker_X1
board_build.ldscript = boards/nrf52840_s140_v7_extrafs.ld
board_upload.maximum_size = 708608
build_flags = ${MeshTracker_X1.build_flags}
  -I examples/companion_radio/ui-orig
  -D QSPIFLASH=1
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_TX_POWER=0
;  -D BLE_DEBUG_LOGGING=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
  -D OFFLINE_QUEUE_SIZE=256
  -D DISPLAY_CLASS=NullDisplayDriver
  -D PIN_BUZZER=25
  -D HAS_DRV2605=1
  -D DRV2605_USE_LRA=1
  -D ADVERT_NAME='"@@MAC"'
build_src_filter = ${MeshTracker_X1.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<helpers/ui/buzzer.cpp>
  +<helpers/ui/NullDisplayDriver.cpp>
  +<helpers/ui/DRV2605Vibration.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-orig/*.cpp>
lib_deps = ${MeshTracker_X1.lib_deps}
  densaugeo/base64 @ ~1.4.0
  stevemarple/MicroNMEA @ ^2.0.6
  end2endzone/NonBlockingRTTTL@^1.3.0
  adafruit/Adafruit DRV2605 Library @ ^1.2.4

[env:MeshTracker_X1_kiss_modem]
extends = MeshTracker_X1
build_src_filter = ${MeshTracker_X1.build_src_filter}
  +<../examples/kiss_modem/>
